### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by lolow** [jackjackk/gdxcompare#1]
when running the command
python -m gdxcompare INDC2020_400.gdx INDC2020_400_bb.gdx

I have:

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lolow/Seafile/WITCH/gdxcompare/gdxcompare.py", line 70, in <module>
    if options.symb_regex[0] == '@':
IndexError: string index out of range

**Comment by jackjackk** [comment]
Thanks, by default there is no filter on symbols loaded (symb_regex='') and the comparison in the second to last line fails.
